### ISSUE TITLE
您好，我这里安装运行后 没办法激活用户

### ISSUE THREAD

**Issue by alex-marmot** [Aufree/ting#3]
您好，我这里安装运行后 没办法激活用户 测试环境UBUNTU12.04  （我是个新手 如果这个问题很逗比，，请谅解下。。）

**Comment by Aufree** [comment]
有两个解决办法:

1. 编辑你的 development.rb 文件, 按照配置写入你的个人邮箱账号, 密码, 建议用 Gmail;
2. 在用户注册时自动激活账号, 参照这里: https://github.com/Aufree/ting/issues/2

**Comment by alex-marmot** [comment]
谢谢。。 搞定了

**Comment by Aufree** [comment]
@alex-marmot 不客气 :)
