### ISSUE TITLE
bug不少

### ISSUE THREAD

**Issue by robbinhan** [Aufree/ting#5]
- 本地跑mail收不到
- 直接输入激活URL会报模板不存在
- songs/new好像没有链接入口
- 添加的时候div挡住了input窗口(mac chrome)

暂时就这些

**Comment by Aufree** [comment]
@robbinhan 你好, 感谢你列举出了这些问题, 我将为你一一解答

1. Mail 需要本地做一下配置之后才可以正常工作, 具体可编辑[此文件](https://github.com/Aufree/ting/blob/master/config/environments/development.rb#L38-L43)并填上自己的 Mail 信息

2. 激活 URL 的问题这边暂时无法重现, 因为之前部署上线的时候刚好遇上 Gmail 被墙, 因此用户在注册后我进行了账号强制设置, 具体可查看[此文件](https://github.com/Aufree/ting/blob/master/app/controllers/users_controller.rb#L59)

3. songs/new 是故意不留链接入口的, 因为发布歌曲的按钮放置在网站左侧, 点击会弹出发布表单, 若有需要你可以在本地添加 new 入口, 可参照[此模板](https://github.com/Aufree/ting/blob/master/app/views/songs/edit.html.slim)进行渲染

4. 看不大懂描述的问题...

**Comment by robbinhan** [comment]
@Aufree hi,

关于第三个回答，我发现如果界面上一个歌曲都没有的情况下是没有『分享歌曲按钮的』
